### ISSUE TITLE
Unexpected cordova plugin add error.

### ISSUE THREAD

**Issue by ronyrun** [driftyco/ionic-plugin-keyboard#131]
Hello, here is the pb 

``` 

users-Mac:wa-user ron$ cordova plugin add ionic-plugin-keyboard
Fetching plugin "ionic-plugin-keyboard" via npm
SyntaxError: Unexpected token v
    at Object.parse (native)
    at getJson (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/util/metadata.js:29:31)
    at Object.exports.save_fetch_metadata (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/util/metadata.js:56:24)
    at /usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/fetch.js:165:18
    at _fulfilled (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:787:54)
    at self.promiseDispatch.done (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:816:30)
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:749:13)
    at /usr/local/lib/node_modules/cordova/node_modules/q/q.js:557:44
    at flush (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:108:17)
    at process._tickCallback (node.js:355:11)

```

**Comment by ronyrun** [comment]
Problem solved, I had the old plugin name in the package.json
