### ISSUE TITLE
Plugin installation failed due to SyntaxError: Unexpected token }

### ISSUE THREAD

**Issue by mrameezraja** [driftyco/ionic-plugin-keyboard#83]
I am getting below error on running 

cordova plugin add com.ionic.keyboard

and unable to install plugin.

SyntaxError: Unexpected token }
    at Object.parse (native)
    at getJson (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/util/metadata.js:29:31)
    at Object.exports.save_fetch_metadata (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/util/metadata.js:56:24)
    at /usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/fetch.js:148:18
    at _fulfilled (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:787:54)
    at self.promiseDispatch.done (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:816:30)
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:749:13)
    at /usr/local/lib/node_modules/cordova/node_modules/q/q.js:557:44
    at flush (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:108:17)
    at process._tickCallback (node.js:419:13)

**Comment by tlancina** [comment]
What version of Cordova are you using?

**Comment by mrameezraja** [comment]
Well i have solved the issue. There is a file 'fetch.json' in plugins folder. There was an extra '}' in it. I just removed it and all went well. 

This was not a issue with ionic keyboard plugin. It doesn't allow me add any plugin.

Thanks

**Comment by nguyenphong1301** [comment]
i have the same issue 
Failed to install 'com.jcjee.plugins.emailcomposer':SyntaxError: Unexpected token <
    at Object.parse (native)
    at Function.PlatformJson.load (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/cordova-common/src/PlatformJson.js:35:21)
    at new PlatformApiPoly (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/platforms/PlatformApiPoly.js:66:39)
    at Object.getPlatformApi (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/platforms/platforms.js:59:23)
    at handleInstall (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/install.js:602:29)
    at /usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/install.js:382:28
    at _fulfilled (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:787:54)
    at self.promiseDispatch.done (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:816:30)
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:749:13)
    at /usr/local/lib/node_modules/cordova/node_modules/q/q.js:509:49
Error: Unexpected token <

and i have tried to install the last version of cordova but not work

**Comment by nkccaomus** [comment]
Yes, I have the same.
i try install plugin other. 
SyntaxError: Unexpected token }
    at Object.parse (native)
    at getJson (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/util/metadata.js:29:31)
    at Object.exports.save_fetch_metadata (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/util/metadata.js:56:24)
    at /usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/fetch.js:165:18
    at _fulfilled (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:787:54)
    at self.promiseDispatch.done (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:816:30)
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:749:13)
    at /usr/local/lib/node_modules/cordova/node_modules/q/q.js:557:44
    at flush (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:108:17)
    at doNTCallback0 (node.js:417:9)

**Comment by vishal41190** [comment]
+1

**Comment by mrameezraja** [comment]
try using "cordova plugin add ionic-plugin-keyboard"

plugin id has been changed to "ionic-plugin-keyboard" from "com.ionic.keyboard".

**Comment by kumaro** [comment]
I experienced this issue today. "cordova plugin add ionic-plugin-keyboard" worked for me

**Comment by nkccaomus** [comment]
I use it ^^
Pulgin because some applications do not have to enter data or packget.json go wrong.
Note that you see ",".

thx.

**Comment by sameerrswt** [comment]
![image](https://cloud.githubusercontent.com/assets/17155131/12939145/3df3c754-cfe2-11e5-8338-ab228148699b.png)

i am getting this error please help.

**Comment by mrameezraja** [comment]
@sameerrswt  use cordova plugin add ionic-plugin-keyboard
